// Pełna lista kategorii zgodna z wymaganiami użytkownika
export const SERVICES_CATALOG = [
  {
    id: "hydraulika",
    label: "Hydraulika",
    children: [
      { slug: "hydraulika-udraznianie-odplywow", label: "Udrażnianie odpływów i kanalizacji", icon: "pipe" },
      { slug: "hydraulika-naprawa-wycieku", label: "Naprawa wycieku", icon: "drop" },
      { slug: "hydraulika-bialy-montaz", label: "Podłączenie zmywarki / pralki (biały montaż)", icon: "washer" },
      { slug: "hydraulika-wymiana-wc", label: "Wymiana WC / spłuczki / mechanizmu", icon: "toilet" },
      { slug: "hydraulika-lokalizacja-wyciekow", label: "Lokalizacja wycieków (kamery, czujniki)", icon: "camera" },
      { slug: "hydraulika-co-odpowietrzanie", label: "Odpowietrzanie i regulacja instalacji c.o.", icon: "radiator" },
      { slug: "hydraulika-serwis-grzejnikow", label: "Wymiana/serwis grzejników i termostatów", icon: "thermostat" },
      { slug: "hydraulika-inne", label: "Inne", icon: "wrench" },
    ],
  },
  {
    id: "elektryka",
    label: "Elektryka",
    children: [
      { slug: "elektryka-montaz-oswietlenia", label: "Montaż gniazdek / włączników / oświetlenia (LED)", icon: "bulb" },
      { slug: "elektryka-wymiana-bezpiecznikow", label: "Wymiana bezpieczników / naprawa rozdzielni", icon: "fuse" },
      { slug: "elektryka-pomiary", label: "Pomiary elektryczne i protokoły", icon: "meter" },
      { slug: "elektryka-smart-home", label: "Smart Home (Tuya/Sonoff) – konfiguracja", icon: "smart" },
      { slug: "elektryka-stacje-ladowania", label: "Stacje ładowania EV – montaż/przegląd", icon: "car" },
      { slug: "elektryka-rtv-sat", label: "RTV/SAT – okablowanie, anteny, wzmacniacze", icon: "monitor" },
      { slug: "elektryka-inne", label: "Inne", icon: "zap" },
    ],
  },
  {
    id: "agd_rtv",
    label: "AGD i RTV",
    children: [
      { slug: "agd-montaz-tv", label: "Montaż TV na ścianie + okablowanie", icon: "monitor" },
      { slug: "agd-konfiguracja-smart", label: "Konfiguracja Smart TV / soundbar / multiroom", icon: "smart" },
      { slug: "agd-instalacja-okapu", label: "Instalacja okapu / zabudowa AGD", icon: "fan" },
      { slug: "agd-naprawa", label: "Naprawa AGD", icon: "wrench" },
      { slug: "agd-naprawa-rtv", label: "Naprawa RTV", icon: "monitor" },
      { slug: "agd-inne", label: "Inne", icon: "wrench" },
    ],
  },
  {
    id: "klimatyzacja_ogrzewanie",
    label: "Klimatyzacja i ogrzewanie",
    children: [
      { slug: "klima-montaz", label: "Montaż klimatyzacji", icon: "snowflake" },
      { slug: "klima-nabicie-czynnika", label: "Nabicie/serwis czynnika, odgrzybianie", icon: "snowflake" },
      { slug: "klima-serwis-pomp", label: "Serwis pomp ciepła", icon: "thermostat" },
      { slug: "klima-regulacja-co", label: "Regulacja/serwis instalacji c.o., sterowniki/termostaty", icon: "thermostat" },
      { slug: "klima-kominiarz", label: "Kominiarz – przeglądy okresowe", icon: "flame" },
      { slug: "klima-inne", label: "Inne", icon: "snowflake" },
    ],
  },
  {
    id: "remont_wykończenia",
    label: "Remont i wykończenia",
    children: [
      { slug: "remont-malowanie", label: "Malowanie", icon: "paintbrush" },
      { slug: "remont-gladzie", label: "Gładzie / szpachlowanie / naprawy ścian", icon: "paintbrush" },
      { slug: "remont-zabudowy-gk", label: "Zabudowy GK / sufity podwieszane", icon: "hammer" },
      { slug: "remont-tynki", label: "Tynki / gips / płyty", icon: "hammer" },
      { slug: "remont-montaz-drzwi", label: "Montaż drzwi / ościeżnic / rolet i karniszy", icon: "hammer" },
      { slug: "remont-silikonowanie", label: "Silikonowanie, fugi, drobne uszczelnienia", icon: "wrench" },
      { slug: "remont-cyklinowanie", label: "Cyklinowanie / renowacja podłóg", icon: "hammer" },
      { slug: "remont-posadzki", label: "Posadzki żywiczne / mikrocement", icon: "hammer" },
      { slug: "remont-montaz-paneli", label: "Montaż paneli", icon: "hammer" },
      { slug: "remont-glazura", label: "Glazura", icon: "hammer" },
      { slug: "remont-naprawa-okien", label: "Naprawa okien", icon: "hammer" },
      { slug: "remont-tapetowanie", label: "Tapetowanie ścian", icon: "paintbrush" },
      { slug: "remont-montaz-listew", label: "Montaż listew", icon: "hammer" },
      { slug: "remont-inne", label: "Inne", icon: "hammer" },
    ],
  },
  {
    id: "stolarstwo_montaz",
    label: "Stolarstwo i montaż",
    children: [
      { slug: "stolarstwo-skladanie-mebli", label: "Składanie mebli", icon: "hammer" },
      { slug: "stolarstwo-naprawa-drzwi", label: "Naprawa/dopasowanie drzwi, zawiasów, prowadnic", icon: "hammer" },
      { slug: "stolarstwo-blaty", label: "Blaty kuchenne, półki na wymiar", icon: "ruler" },
      { slug: "stolarstwo-zabudowy", label: "Zabudowy i szafy wnękowe (prosty montaż)", icon: "hammer" },
      { slug: "stolarstwo-listwy", label: "Listwy przypodłogowe, progi, cokoły", icon: "hammer" },
      { slug: "stolarstwo-karnisze", label: "Montaż karniszy / rolet / żaluzji", icon: "hammer" },
      { slug: "stolarstwo-inne", label: "Inne", icon: "hammer" },
    ],
  },
  {
    id: "slusarz_zabezpieczenia",
    label: "Ślusarz i zabezpieczenia",
    children: [
      { slug: "slusarz-otwieranie-drzwi", label: "Awaryjne otwieranie drzwi", icon: "lock" },
      { slug: "slusarz-wymiana-zamka", label: "Wymiana zamka", icon: "lock" },
      { slug: "slusarz-zamki-antywlamaniowe", label: "Montaż zamków antywłamaniowych", icon: "lock" },
      { slug: "slusarz-wizjery", label: "Wizjery / wideodomofony / samozamykacze", icon: "camera" },
      { slug: "slusarz-sejfy", label: "Sejfy – montaż/serwis", icon: "lock" },
      { slug: "slusarz-naprawa-rolet", label: "Naprawa rolet zewnętrznych (zabezpieczenia)", icon: "lock" },
      { slug: "slusarz-inne", label: "Inne", icon: "lock" },
    ],
  },
  {
    id: "sprzatanie",
    label: "Sprzątanie",
    children: [
      { slug: "sprzatanie-mieszkanie", label: "Sprzątanie mieszkania", icon: "sparkles" },
      { slug: "sprzatanie-po-remoncie", label: "Sprzątanie po remoncie / po wyprowadzce", icon: "sparkles" },
      { slug: "sprzatanie-biura", label: "Sprzątanie biur / lokali usługowych", icon: "sparkles" },
      { slug: "sprzatanie-pranie-dywanow", label: "Pranie dywanów / materacy / ozonowanie", icon: "sparkles" },
      { slug: "sprzatanie-mycie-okien", label: "Mycie okien", icon: "sparkles" },
      { slug: "sprzatanie-pranie-tapicerki", label: "Pranie tapicerki", icon: "sparkles" },
      { slug: "sprzatanie-piwnice-strychy", label: "Sprzątanie piwnic/strychów", icon: "sparkles" },
      { slug: "sprzatanie-inne", label: "Inne", icon: "sparkles" },
    ],
  },
  {
    id: "dom_ogrod",
    label: "Dom i ogród",
    children: [
      { slug: "ogrod-pielegnacja", label: "Pielęgnacja ogrodu", icon: "leaf" },
      { slug: "ogrod-projekt", label: "Projekt ogrodu (koncepcja + nasadzenia)", icon: "leaf" },
      { slug: "ogrod-mala-architektura", label: "Mała architektura (taras, pergola, ścieżki)", icon: "ruler" },
      { slug: "ogrod-nawadnianie", label: "Koncepcja systemu nawadniania", icon: "droplets" },
      { slug: "ogrod-trawnik", label: "Zakładanie trawnika / wertykulacja / aeracja", icon: "leaf" },
      { slug: "ogrod-systemy-nawadniania", label: "Systemy nawadniania – montaż/serwis", icon: "droplets" },
      { slug: "ogrod-ogrodzenia", label: "Montaż/naprawa ogrodzeń i bram", icon: "hammer" },
      { slug: "ogrod-altany", label: "Altany / tarasy – naprawy i olejowanie", icon: "hammer" },
      { slug: "ogrod-odśnieżanie", label: "Odśnieżanie", icon: "snowflake" },
      { slug: "ogrod-koszenie", label: "Koszenie trawnika", icon: "leaf" },
      { slug: "ogrod-przycinanie", label: "Przycinanie krzewów", icon: "leaf" },
      { slug: "ogrod-usuwanie-gniazd", label: "Usuwanie gniazd os/szerszeni", icon: "bug" },
      { slug: "ogrod-czyszczenie-pieca", label: "Czyszczenie pieca", icon: "flame" },
      { slug: "ogrod-czyszczenie-dachu", label: "Czyszczenie dachu", icon: "hammer" },
      { slug: "ogrod-grabienie-lisci", label: "Grabienie liści", icon: "leaf" },
      { slug: "ogrod-moskitiery", label: "Moskitiery", icon: "hammer" },
      { slug: "ogrod-inne", label: "Inne", icon: "leaf" },
    ],
  },
  {
    id: "auto_mobilne",
    label: "Auto mobilne",
    children: [
      { slug: "auto-wymiana-akumulatora", label: "Wymiana akumulatora", icon: "car" },
      { slug: "auto-wymiana-kola", label: "Wymiana koła", icon: "car" },
      { slug: "auto-wymiana-opon", label: "Wymiana opon/koła na miejscu (sezonowo)", icon: "car" },
      { slug: "auto-rozruch", label: "Rozruch z kabli", icon: "car" },
      { slug: "auto-holowanie", label: "Holowanie / 'laweta light' w mieście", icon: "truck" },
      { slug: "auto-diagnostyka", label: "Diagnostyka OBD (proste odczyty)", icon: "monitor" },
      { slug: "auto-wymiana-czesci", label: "Wymiana żarówek / wycieraczek / bezpieczników", icon: "car" },
      { slug: "auto-myjnia", label: "Myjnia mobilna / szybkie detailing mini", icon: "droplets" },
      { slug: "auto-dowoz-paliwa", label: "Dowóz paliwa", icon: "car" },
      { slug: "auto-inne", label: "Inne", icon: "car" },
    ],
  },
  {
    id: "it",
    label: "IT",
    children: [
      { slug: "it-naprawa-laptopow", label: "Naprawa laptopów/PC (czyszczenie, termopasty)", icon: "laptop" },
      { slug: "it-instalacja-systemu", label: "Instalacja systemu, sterowników, Office", icon: "laptop" },
      { slug: "it-usuwanie-wirusow", label: "Usuwanie wirusów / malware", icon: "shield" },
      { slug: "it-konfiguracja-wifi", label: "Konfiguracja Wi-Fi / drukarki / sieci mesh", icon: "wifi" },
      { slug: "it-backup", label: "Backup w chmurze, odzysk podstawowy danych", icon: "cloud" },
      { slug: "it-konfiguracja-telefonu", label: "Konfiguracja telefonu / migracja danych", icon: "smartphone" },
      { slug: "it-smart-home-konfiguracja", label: "Smart Home – konfiguracja aplikacji i scen", icon: "cpu" },
      { slug: "it-inne", label: "Inne", icon: "laptop" },
    ],
  },
  {
    id: "zdrowie",
    label: "Zdrowie",
    children: [
      { slug: "zdrowie-telekonsultacja", label: "Telekonsultacja lekarza", icon: "stethoscope" },
      { slug: "zdrowie-wizyty-domowe", label: "Wizyty domowe (opieka podstawowa)", icon: "stethoscope" },
      { slug: "zdrowie-wizyty-pielegniarskie", label: "Wizyty pielęgniarskie (zastrzyki, opatrunki)", icon: "stethoscope" },
      { slug: "zdrowie-fizjoterapeuta", label: "Fizjoterapeuta domowy", icon: "heart" },
      { slug: "zdrowie-asystent-seniora", label: "Asystent seniora / towarzyszenie", icon: "heart" },
      { slug: "zdrowie-inne", label: "Inne", icon: "stethoscope" },
    ],
  },
  {
    id: "zwierzeta",
    label: "Zwierzęta",
    children: [
      { slug: "zwierzeta-konsultacja-weterynaryjna", label: "Konsultacja weterynaryjna", icon: "paw-print" },
      { slug: "zwierzeta-wyprowadzanie-psa", label: "Wyprowadzanie psa (regularnie / jednorazowo)", icon: "paw-print" },
      { slug: "zwierzeta-opieka-dzienna", label: "Opieka dzienna / wyjazdowa (pet sitting)", icon: "paw-print" },
      { slug: "zwierzeta-wizyty-karmienie", label: "Wizyty karmienie / czyszczenie kuwety", icon: "paw-print" },
      { slug: "zwierzeta-transport", label: "Transport do weterynarza", icon: "truck" },
      { slug: "zwierzeta-groomer", label: "Groomer mobilny / strzyżenie", icon: "scissors" },
      { slug: "zwierzeta-behawiorysta", label: "Behawiorysta / trening podstawowy", icon: "paw-print" },
      { slug: "zwierzeta-weterynarz-domowy", label: "Weterynarz domowy", icon: "stethoscope" },
      { slug: "zwierzeta-inne", label: "Inne", icon: "paw-print" },
    ],
  },
  {
    id: "dezynsekcja_szkodniki",
    label: "Dezynsekcja/szkodniki",
    children: [
      { slug: "dezynsekcja-pluskwy", label: "Zwalczanie pluskiew / karaluchów / prusaków", icon: "bug" },
      { slug: "dezynsekcja-mrowki", label: "Zwalczanie mrówek / rybików", icon: "bug" },
      { slug: "dezynsekcja-osy", label: "Osy / szerszenie – bezpieczne usuwanie", icon: "bug" },
      { slug: "dezynsekcja-deratyzacja", label: "Deratyzacja (gryzonie) + monitoring HACCP", icon: "bug" },
      { slug: "dezynsekcja-zabezpieczenia", label: "Zabezpieczenia po inwazji (siatki, uszczelnienia)", icon: "shield" },
      { slug: "dezynsekcja-inne", label: "Inne", icon: "bug" },
    ],
  },
  {
    id: "przeprowadzki_transport",
    label: "Przeprowadzki i transport",
    children: [
      { slug: "przeprowadzki-taxi-bagazowe", label: "Taxi bagażowe (małe przeprowadzki)", icon: "truck" },
      { slug: "przeprowadzki-transport-gabarytow", label: "Transport gabarytów", icon: "truck" },
      { slug: "przeprowadzki-demontaz-montaz", label: "Demontaż/montaż mebli, pakowanie", icon: "hammer" },
      { slug: "przeprowadzki-wnoszenie-znoszenie", label: "Wnoszenie / znoszenie (ekipy)", icon: "truck" },
      { slug: "przeprowadzki-kurier-miejski", label: "Kurier miejski (ekspres lokalny)", icon: "truck" },
      { slug: "przeprowadzki-inne", label: "Inne", icon: "truck" },
    ],
  },
  {
    id: "gaz",
    label: "Gaz",
    children: [
      { slug: "gaz-przeglad", label: "Przegląd instalacji", icon: "flame" },
      { slug: "gaz-wyciek", label: "Wyciek gazu", icon: "flame" },
      { slug: "gaz-montaz-kuchenki", label: "Montaż kuchenki gazowej", icon: "flame" },
      { slug: "gaz-wymiana-reduktorow", label: "Wymiana reduktorów / węży", icon: "wrench" },
      { slug: "gaz-proby-szczelnosci", label: "Próby szczelności i protokoły", icon: "gauge" },
      { slug: "gaz-inne", label: "Inne", icon: "flame" },
    ],
  },
  {
    id: "wywoz_utylizacja",
    label: "Wywóz/utylizacja",
    children: [
      { slug: "wywoz-gruz", label: "Wywóz gruzu / kontener", icon: "trash-2" },
      { slug: "wywoz-gabaryty", label: "Wywóz gabarytów / mebli", icon: "trash-2" },
      { slug: "wywoz-elektrosmieci", label: "Utylizacja elektrośmieci (AGD/RTV)", icon: "trash-2" },
      { slug: "wywoz-zielen", label: "Wywóz zieleni / gałęzi", icon: "trash-2" },
      { slug: "wywoz-czyszczenie-piwnic", label: "Czyszczenie piwnic/strychów", icon: "trash-2" },
      { slug: "wywoz-zlom", label: "Wywóz złomu", icon: "trash-2" },
      { slug: "wywoz-fekalia", label: "Wywóz fekalii", icon: "trash-2" },
      { slug: "wywoz-inne", label: "Inne", icon: "trash-2" },
    ],
  },
  {
    id: "pomoc_24h",
    label: "Pomoc 24/7",
    children: [
      { slug: "pomoc-awaria-hydrauliczna", label: "Awaria hydrauliczna (wyciek)", icon: "droplets" },
      { slug: "pomoc-awaria-elektryczna", label: "Awaria elektryczna (zabezpieczenia)", icon: "zap" },
      { slug: "pomoc-otwieranie-drzwi", label: "Awaryjne otwieranie drzwi (ślusarz)", icon: "lock" },
      { slug: "pomoc-pomoc-drogowa", label: "Pomoc drogowa / rozruch / koło", icon: "car" },
      { slug: "pomoc-zabezpieczenie-po-zalaniu", label: "Zabezpieczenie po zalaniu / dachu", icon: "droplets" },
      { slug: "pomoc-inne", label: "Inne", icon: "clock" },
    ],
  },
  {
    id: "zlota_raczka",
    label: "Złota rączka",
    children: [
      { slug: "zlota-raczka-montaz-tv", label: "Montaż TV / karniszy / rolet / obrazów", icon: "hammer" },
      { slug: "zlota-raczka-drobne-naprawy", label: "Drobne naprawy w domu (zawiasy, zamki meblowe)", icon: "wrench" },
      { slug: "zlota-raczka-silikonowanie", label: "Silikonowanie, uszczelnienia, poprawki", icon: "wrench" },
      { slug: "zlota-raczka-skrecanie-mebli", label: "Skręcanie mebli / półki / uchwyty", icon: "hammer" },
      { slug: "zlota-raczka-godzina-domu", label: "Godzina dla domu (mix drobiazgów)", icon: "clock" },
      { slug: "zlota-raczka-inne", label: "Inne", icon: "wrench" },
    ],
  },
  {
    id: "codzienne-sprawy",
    label: "Codzienne sprawy",
    children: [
      { slug: "codzienne-zakupy",                    label: "Zakupy na szybko",                               icon: "shopping-cart" },
      { slug: "codzienne-odbior-zwrot-paczek",       label: "Odbiór/zwrot paczek",                            icon: "package" },
      { slug: "codzienne-pomoc-przeprowadzce-light", label: "Pomoc przy przeprowadzce light (pudełka)",       icon: "package" },
      { slug: "codzienne-drobne-porzadki",           label: "Drobne porządki",                                icon: "sparkles" },
      { slug: "codzienne-inne",                      label: "Inne",                                            icon: "shopping-cart" }
    ],
  },
  {
    id: "urzedy_formalnosci",
    label: "Urzędy i formalności",
    children: [
      { slug: "urzedy-wypelnianie-wnioskow", label: "Wypełnianie wniosków / ePUAP / profil zaufany", icon: "file-text" },
      { slug: "urzedy-rejestracja-auta", label: "Rejestracja auta / dowód rejestracyjny", icon: "file-text" },
      { slug: "urzedy-tlumaczenie", label: "Tłumaczenie krótkich pism (nie-przysięgłe)", icon: "file-text" },
      { slug: "urzedy-umawianie-wizyt", label: "Umawianie wizyt / rezerwacje", icon: "calendar" },
      { slug: "urzedy-inne", label: "Inne", icon: "file-text" },
    ],
  },
  {
    id: "edukacja_korepetycje",
    label: "Edukacja i korepetycje",
    children: [
      { slug: "edukacja-matematyka", label: "Matematyka / języki / matura", icon: "graduation-cap" },
      { slug: "edukacja-nauka-komputera", label: "Nauka obsługi komputera/telefonu", icon: "laptop" },
      { slug: "edukacja-zadania-domowe", label: "Pomoc \"zadania domowe\"", icon: "book" },
      { slug: "edukacja-kursy-krotkie", label: "Kursy krótkie (Excel, CV/LinkedIn)", icon: "laptop" },
      { slug: "edukacja-inne", label: "Inne", icon: "graduation-cap" },
    ],
  },
  {
    id: "rower_hulajnoga",
    label: "Rower / hulajnoga",
    children: [
      { slug: "rower-serwis", label: "Serwis roweru (hamulce, przerzutki)", icon: "bike" },
      { slug: "rower-wymiana-detki", label: "Wymiana dętki / opony", icon: "bike" },
      { slug: "rower-konserwacja-hulajnogi", label: "Konserwacja hulajnogi elektrycznej", icon: "bike" },
      { slug: "rower-inne", label: "Inne", icon: "bike" },
    ],
  },
  {
    id: "monitoring_alarmy",
    label: "Monitoring i alarmy",
    children: [
      { slug: "monitoring-montaz-kamer", label: "Montaż kamer / wideodomofonów", icon: "camera" },
      { slug: "monitoring-konfiguracja-alarmu", label: "Konfiguracja alarmu / czujników", icon: "shield" },
      { slug: "monitoring-inne", label: "Inne", icon: "camera" },
    ],
  },
  {
    id: "akwarystyka",
    label: "Akwarystyka",
    children: [
      { slug: "akwarystyka-zakladanie", label: "Zakładanie i start akwarium", icon: "fish" },
      { slug: "akwarystyka-aranzacja", label: "Aranżacja / aquascaping", icon: "fish" },
      { slug: "akwarystyka-podmiany-wody", label: "Podmiany wody i serwis cykliczny", icon: "droplets" },
      { slug: "akwarystyka-inne", label: "Inne", icon: "fish" },
    ],
  },
  {
    id: "wynajem",
    label: "Wynajem",
    children: [
      { slug: "wynajem-przyczepy", label: "Wynajem przyczep i lawet", icon: "truck" },
      { slug: "wynajem-maszyny-budowlane", label: "Wynajem maszyn budowlanych", icon: "hammer" },
      { slug: "wynajem-narzedzia", label: "Wynajem narzędzi i ogrodowych", icon: "wrench" },
      { slug: "wynajem-foto-video", label: "Wynajem foto-video/AV", icon: "camera" },
      { slug: "wynajem-sprzet-eventowy", label: "Wynajem sprzętu eventowego", icon: "music" },
      { slug: "wynajem-sport-outdoor", label: "Wynajem sport/outdoor", icon: "mountain" },
      { slug: "wynajem-samochod", label: "Wynajem samochodu", icon: "car" },
      { slug: "wynajem-inne", label: "Inne", icon: "package" },
    ],
  },
  {
    id: "architektura",
    label: "Architektura",
    children: [
      { slug: "architektura-konsultacje", label: "Konsultacje online", icon: "ruler" },
      { slug: "architektura-projekt-koncepcyjny", label: "Projekt koncepcyjny mieszkania/pokoju", icon: "ruler" },
      { slug: "architektura-wizualizacje", label: "Wizualizacje 3D", icon: "monitor" },
      { slug: "architektura-inwentaryzacja", label: "Inwentaryzacja pomiarowa 2D/3D", icon: "ruler" },
      { slug: "architektura-audyt", label: "Audyt funkcjonalny lokalu/usługu (układ ścian, strefy)", icon: "ruler" },
      { slug: "architektura-projekt-budowlany", label: "Projekt budowlany / przebudowa", icon: "ruler" },
      { slug: "architektura-inne", label: "Inne", icon: "ruler" },
    ],
  },
  {
    id: "webinary_szkolenia",
    label: "Webinary i szkolenia",
    children: [
      { slug: "webinary-szkolenie-online", label: "Szkolenie online", icon: "monitor" },
      { slug: "webinary-warsztat-grupowy", label: "Warsztat grupowy online", icon: "users" },
      { slug: "webinary-webinarium", label: "Webinarium", icon: "presentation" },
      { slug: "webinary-kurs-online", label: "Kurs online", icon: "book" },
      { slug: "webinary-szkolenie-zawodowe", label: "Szkolenie zawodowe", icon: "briefcase" },
      { slug: "webinary-masterclass", label: "Masterclass", icon: "award" },
      { slug: "webinary-konsultacja-grupowa", label: "Konsultacja grupowa", icon: "users" },
      { slug: "webinary-inne", label: "Inne", icon: "monitor" },
    ],
  },
  {
    id: "inne",
    label: "Inne",
    children: [
      { slug: "inne-opisz-problem", label: "Inne opisz problem", icon: "plus-circle" },
    ],
  },
];

// Szybki lookup po slugach
export const SERVICE_BY_SLUG = SERVICES_CATALOG.flatMap(c => c.children).reduce((acc, s) => {
  acc[s.slug] = s;
  return acc;
}, {});